version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    networks:
      - app-network
    depends_on:
      - backend
    volumes:
      - ./frontend:/app:delegated
      - frontend_node_modules:/app/node_modules

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=auth_db
      - JWT_SECRET=your-secret-key
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-optional}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-optional}
    networks:
      - app-network
    depends_on:
      - db
    volumes:
      - ./backend:/app:delegated
      - backend_node_modules:/app/node_modules

  db:
    image: postgres:13-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth_db
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  frontend_node_modules:
  backend_node_modules: 