version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    networks:
      - app-network
    depends_on:
      - backend
    volumes:
      - ./frontend:/app:delegated
      - frontend_node_modules:/app/node_modules

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: your-secret-key
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID:-optional}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET:-optional}
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app:delegated
      - backend_node_modules:/app/node_modules

  db:
    image: postgres
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
  frontend_node_modules:
  backend_node_modules: 